# Customize color scheme for Joestar
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[command]='fg=#DC8DF5'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#DC8DF5'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#FFD75D'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#DC8DF5'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#DC8DF5'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#DC8DF5'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#FFD75D'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#DC8DF5'
ZSH_HIGHLIGHT_STYLES[function]='fg=#DC8DF5'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#726D8F'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#726D8F'
ZSH_HIGHLIGHT_STYLES[command-substitution]='fg=#DC8DF5'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#FFD75D'
ZSH_HIGHLIGHT_STYLES[path]='fg=#DC8DF5'
ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#33E5E5'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#33E5E5'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#33E5E5'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#33E5E5'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#3AEB94'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#3AEB94'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#3AEB94'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#FFD75D'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#FFD75D'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#FFD75D'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#3AEB94'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#786EC9'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#3AEB94'