# Customize color scheme for Joestar
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[command]='fg=125'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=60'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=125'
ZSH_HIGHLIGHT_STYLES[alias]='fg=176'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=176'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=176'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=220'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=176'
ZSH_HIGHLIGHT_STYLES[function]='fg=176'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=60'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=60'
ZSH_HIGHLIGHT_STYLES[command-substitution]='fg=176'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=220'
ZSH_HIGHLIGHT_STYLES[path]='fg=?'
ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=51'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=51'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=51'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=51'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=43'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=43'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=43'
ZSH_HIGHLIGHT_STYLES[assign]='fg=220'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=220'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=220'
ZSH_HIGHLIGHT_STYLES[comment]='fg=43'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=61'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=43'